api/config/routes.rb
Rails.application.routes.draw do
  resources :group_chats
  resources :private_chats
  resources :comments
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/users/follow', to: 'follow#follow_user'
  get 'users/:id/following', to: 'follow#following_list'
  get 'users/:id/followers', to: 'follow#followers_list'
  get 'users/:id/verbose_info', to: 'users#show_verbose'

  post '/auth/login', to: 'authentication#login'
  get '/auth/verify', to: 'authentication#verify'
  get '/auth/verify/verbose-info', to: 'authentication#verify_and_verbose_info'

  # PRIVATE CHATS
  post '/private_chat/send_message', to: 'private_chats#send_private_message'
  post '/private_chat/conversation', to: 'private_chats#show'
  # GROUP CHATS
  get '/private_chat/:id/all_active_chats',to: 'private_chats#all_current_user_chats'

  # To make sure a parameter matches a regular expression
  # resources :users, constraints: { id: /[A-Z]/}
  # Look into member and collection block to add unique restful actions 

  resources :users do
    member do
      get :posts, :comments
    end

  end

  resources :posts do
    resources :comments
    
  end
  # Use this when creating the posts model/controllers
  # resources :users do
  #   resources :posts, shallow: true
  # end


  # Defines the root path route ("/")
  resolve('User') {[:user]}
  # root "articles#index"
end

api/app/models/group_chat.rb
class GroupChat < ApplicationRecord
  has_many :users
  has_many :messages
end

api/app/controllers/group_chats_controller.rb
class GroupChatsController < ApplicationController
  before_action :set_group_chat, only: %i[ show edit update destroy ]

  # GET /group_chats or /group_chats.json
  def index
    @group_chats = GroupChat.all
  end

  # GET /group_chats/1 or /group_chats/1.json
  def show
  end

  # GET /group_chats/new
  def new
    @group_chat = GroupChat.new
  end

  # GET /group_chats/1/edit
  def edit
  end

  # POST /group_chats or /group_chats.json
  def create
    @group_chat = GroupChat.new(group_chat_params)

    respond_to do |format|
      if @group_chat.save
        format.html { redirect_to group_chat_url(@group_chat), notice: "Group chat was successfully created." }
        format.json { render :show, status: :created, location: @group_chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_chats/1 or /group_chats/1.json
  def update
    respond_to do |format|
      if @group_chat.update(group_chat_params)
        format.html { redirect_to group_chat_url(@group_chat), notice: "Group chat was successfully updated." }
        format.json { render :show, status: :ok, location: @group_chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_chats/1 or /group_chats/1.json
  def destroy
    @group_chat.destroy

    respond_to do |format|
      format.html { redirect_to group_chats_url, notice: "Group chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_chat
      @group_chat = GroupChat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_chat_params
      params.fetch(:group_chat, {})
    end
end

api/app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

api/app/views/group_chats/_form.html.erb
<%= form_with(model: group_chat) do |form| %>
  <% if group_chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_chat.errors.count, "error") %> prohibited this group_chat from being saved:</h2>

      <ul>
        <% group_chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

api/app/views/group_chats/_group_chat.html.erb
<div id="<%= dom_id group_chat %>">
</div>

api/app/views/group_chats/edit.html.erb
<h1>Editing group chat</h1>

<%= render "form", group_chat: @group_chat %>

<br>

<div>
  <%= link_to "Show this group chat", @group_chat %> |
  <%= link_to "Back to group chats", group_chats_path %>
</div>

api/app/views/group_chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Group chats</h1>

<div id="group_chats">
  <% @group_chats.each do |group_chat| %>
    <%= render group_chat %>
    <p>
      <%= link_to "Show this group chat", group_chat %>
    </p>
  <% end %>
</div>

<%= link_to "New group chat", new_group_chat_path %>

api/app/views/group_chats/new.html.erb
<h1>New group chat</h1>

<%= render "form", group_chat: @group_chat %>

<br>

<div>
  <%= link_to "Back to group chats", group_chats_path %>
</div>

api/app/views/group_chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_chat %>

<div>
  <%= link_to "Edit this group chat", edit_group_chat_path(@group_chat) %> |
  <%= link_to "Back to group chats", group_chats_path %>

  <%= button_to "Destroy this group chat", @group_chat, method: :delete %>
</div>