api/config/routes.rb
Rails.application.routes.draw do
  resources :group_chats
  resources :private_chats
  resources :comments
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/users/follow', to: 'follow#follow_user'
  get 'users/:id/following', to: 'follow#following_list'
  get 'users/:id/followers', to: 'follow#followers_list'
  get 'users/:id/verbose_info', to: 'users#show_verbose'

  post '/auth/login', to: 'authentication#login'
  get '/auth/verify', to: 'authentication#verify'
  get '/auth/verify/verbose-info', to: 'authentication#verify_and_verbose_info'

  # PRIVATE CHATS
  post '/private_chat/send_message', to: 'private_chats#send_private_message'
  post '/private_chat/conversation', to: 'private_chats#show'
  # GROUP CHATS
  get '/private_chat/:id/all_active_chats',to: 'private_chats#all_current_user_chats'

  # To make sure a parameter matches a regular expression
  # resources :users, constraints: { id: /[A-Z]/}
  # Look into member and collection block to add unique restful actions 

  resources :users do
    member do
      get :posts, :comments
    end

  end

  resources :posts do
    resources :comments
    
  end
  # Use this when creating the posts model/controllers
  # resources :users do
  #   resources :posts, shallow: true
  # end


  # Defines the root path route ("/")
  resolve('User') {[:user]}
  # root "articles#index"
end

api/app/models/private_chat.rb
class PrivateChat < ApplicationRecord
  # belongs_to :user, foreign_key: :sender_id, class_name: 'User'
  # belongs_to :user, foreign_key: :recipient_id, class_name: 'User'
  has_many :messages, dependent: :delete_all

 
  def current_users_chats(array_of_messages)

    # array_of_conversations = []
    # array_of_messages.sort_by!(&:created_at)
    return array_of_messages.sort_by(&:created_at).group_by do |message|
        message.recipient_id
       end

  end

end

api/app/controllers/private_chats_controller.rb
class PrivateChatsController < ApplicationController
  before_action :set_private_chat, only: %i[ edit update destroy ]
  before_action :authorize_request, only: %i[ all_current_user_chats]

  # GET /private_chats/1 or /private_chats/1.json
  def show
    @conversation = Message.where(sender_id: params[:sender_id], recipient_id: params[:recipient_id]).or(Message.where(sender_id: params[:recipient_id], recipient_id: params[:sender_id])).sort_by {|mes| mes[:id]}
    render json: @conversation.as_json(include: {
    sender: {},
    recipient: {}
    })
  end

  # GET /private_chat/all_current_user_chats/:id
  def all_current_user_chats
    # Get ALL messages where sender is equal to current user id, then organize them?
    @all_users_chats = Message.where(sender_id: params[:id]).or(Message.where(recipient_id: params[:id])).order(created_at: :desc)
    @all_users_chats = @all_users_chats.group_by do |message|
      if @current_user.username == message.recipient.username 
        message.sender.username 
      else
        message.recipient.username 
      end
    end
    
    render json: @all_users_chats.as_json(include: {
      sender: {
        methods: :profile_picture_url
      }, 
      recipient: {
        methods: :profile_picture_url
      }
    })

  end


  def send_private_message
    @message = Message.new(private_chat_params)
    @message.content = params[:content]



    if @message.save
      render json: @message.as_json()
    else
      render json: {message: @message.errors, data: @message.as_json()}
    end
  end




  # DELETE /private_chats/1 or /private_chats/1.json
  def destroy
    @private_chat.destroy

    respond_to do |format|
      format.html { redirect_to private_chats_url, notice: "Private chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender_private_chat
      @sender_private_chat = PrivateChat.find(sender_id: params[:sender_id], recipient_id: params[:recipient_id])
    end

    def set_recipient_private_chat
      @recipient_private_chat = PrivateChat.find(sender_id: params[:recipient_id], recipient_id: params[:sender_id])
    end

      # Only allow a list of trusted parameters through.
    def private_chat_params
      params.require(:private_chat).permit(:sender_id, :recipient_id, :content, :id)
    end

    def message_params
      params.require(:message).permit(:content, :sender_id, :recipient_id)
    end
end

api/app/helpers/private_chats_helper.rb
module PrivateChatsHelper
end

api/app/views/private_chats/_form.html.erb
<%= form_with(model: private_chat) do |form| %>
  <% if private_chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(private_chat.errors.count, "error") %> prohibited this private_chat from being saved:</h2>

      <ul>
        <% private_chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

api/app/views/private_chats/_private_chat.html.erb
<div id="<%= dom_id private_chat %>">
</div>

api/app/views/private_chats/edit.html.erb
<h1>Editing private chat</h1>

<%= render "form", private_chat: @private_chat %>

<br>

<div>
  <%= link_to "Show this private chat", @private_chat %> |
  <%= link_to "Back to private chats", private_chats_path %>
</div>

api/app/views/private_chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Private chats</h1>

<div id="private_chats">
  <% @private_chats.each do |private_chat| %>
    <%= render private_chat %>
    <p>
      <%= link_to "Show this private chat", private_chat %>
    </p>
  <% end %>
</div>

<%= link_to "New private chat", new_private_chat_path %>

api/app/views/private_chats/new.html.erb
<h1>New private chat</h1>

<%= render "form", private_chat: @private_chat %>

<br>

<div>
  <%= link_to "Back to private chats", private_chats_path %>
</div>

api/app/views/private_chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @private_chat %>

<div>
  <%= link_to "Edit this private chat", edit_private_chat_path(@private_chat) %> |
  <%= link_to "Back to private chats", private_chats_path %>

  <%= button_to "Destroy this private chat", @private_chat, method: :delete %>
</div>